
<style>
    <?php include 'stylesheets/listFilms.css';?>
    <?php include 'stylesheets/category.css';?>
</style>

<div class="list-card">
    <h3>Delete category</h3>
</div>

<div class="options-btn">
    <a href="<?= $this->baseUrl() ?>/createCategories"><i class="fa-solid fa-square-plus fa-lg"></i> Create Category</a>
    <a href="<?= $this->baseUrl() ?>/updateCategories"><i class="fa-solid fa-wrench fa-lg"></i> Update Category</a>
</div>

<?php $categoryData = Category::allCategory(); ?>

<div class="list-films-container">
    <?php foreach($categoryData as $category): ?>
        <div class="movie-card">
            <img src="<?= str_replace('\/', '/', $category['urlCategoryImg']); ?>" alt="<?= $category['name']; ?>">
            <h3><?= $category['name']; ?></h3>
            <div class="add-film-container">
                <button>    
                <a href="<?= $this->baseUrl() ?>/deleteCategories?id=<?= $category['id']; ?>">Delete</a>
                </button>
            </div>
        </div>
        <?php endforeach; ?>
</div>
