
<style>
    <?php include 'stylesheets/style.css'; ?>
</style>

<div class="submenu">
    <a href="<?= $this->baseUrl() ?>/createCategories">Create category</a>
    <a href="<?= $this->baseUrl() ?>/updateCategories">Update category</a>
</div>

<?php $categoryData = Category::allCategory(); ?>

<div class="container">
    <h2>Delete category</h2>
</div>

<div class="list-container">
    <?php foreach($categoryData as $category): ?>
        <div class="movie-card">
            <img src="<?= str_replace('\/', '/', $category['urlCategoryImg']); ?>" alt="<?= $category['name']; ?>">
            <button><a href="<?= $this->baseUrl() ?>/deleteCategories?id=<?= $category['id']; ?>">Delete</a></button>
            <h3><?= $category['name']; ?></h3>
            <p><?= $category['description']; ?></p>
        </div>
    <?php endforeach; ?>
</div>
