<style>
    <?php include 'stylesheets/card.css'; ?>
</style>

<div id="card">
    <h3>Login </h3>

    <form method="post" action="<?= $this->baseUrl() ?>/login">

        <input type="text" id="username" name="username" placeholder="Username" required>


        <input type="password" id="password" name="password" placeholder="Password" required>

        <button type="submit" class="button" loginAction>Login</button>
    </form>
</div>
