
<style>
    <?php include 'stylesheets/category.css'; ?>
</style>

<div class="options-btn">
    <button><a href="<?= $this->baseUrl() ?>/createCategories">Create Categories</a></button>
    <button><a href="<?= $this->baseUrl() ?>/updateCategories">Update Categories</a></button>
    <button><a href="<?= $this->baseUrl() ?>/deleteCategories">Delete Categories</a></button>
</div>

<?php $categoryData = Category::allCategory()?>

<div class="add-cat-container">
    <h2>List of Categories</h2>
</div>

<div class="list-films-container">
    <?php foreach($categoryData as $category): ?>
        <div class="movie-card">
            <p value="<?= $category['id']; ?>">
                <img src="<?= str_replace('\/', '/', $category['urlCategoryImg']); ?>"
                    alt="<?= $category['name']; ?>" 
                    style="width: 100%; height: auto;">
            </p>
            <p value="<?= $category['id']; ?>"><?= $category['name']; ?></p>
            <p value="<?= $category['id']; ?>"><?= $category['description']; ?></p>
        </div>
    <?php endforeach; ?>
</div>
