
<style>
    <?php include 'stylesheets/style.css';?>
</style>

<div class="submenu">
    <a href="<?= $this->baseUrl() ?>/createCategories">Create Category</a>
    <a href="<?= $this->baseUrl() ?>/updateCategories">Update Category</a>
    <a href="<?= $this->baseUrl() ?>/deleteCategories">Delete Category</a>
</div>

<?php $categoryData = Category::allCategory()?>

<div class="container">
    <h2>List Categories</h2>
</div>

<div class="list-container">
    <?php foreach($categoryData as $category): ?>
        <div class="movie-card">
            <p value="<?= $category['id']; ?>">
                <img src="<?= str_replace('\/', '/', $category['urlCategoryImg']); ?>"
                    alt="<?= $category['name']; ?>" 
                    style="width: 100%; height: auto;">
            </p>
            <h3 value="<?= $category['id']; ?>"><?= $category['name']; ?></h3>
            <p value="<?= $category['id']; ?>"><?= $category['description']; ?></p>
        </div>
    <?php endforeach; ?>
</div>
