<style>
    <?php include 'stylesheets/category.css'; ?>
</style>

<div class="options-btn">
    <button><a href="<?= $this->baseUrl() ?>/createCategories">Create Categories</a></button>
    <button><a href="<?= $this->baseUrl() ?>/updateCategories">Update Categories</a></button>
    <button><a href="<?= $this->baseUrl() ?>/deleteCategories">Delete Categories</a></button>
</div>

<div class="add-film-container">
    <h2>Create Category</h2>
        <form method="post" action="<?= $this->baseUrl() ?>/createCategories" enctype="multipart/form-data">
            <label for="name">Name</label>
            <input type="text" id="name" name="name" required>
            
            <label for="description">Description</label>
            <input type="text" id="description" name="description" required>
            <!-- <textarea type="text" id="description" name="description" rows="3" cols="43" required></textarea><br><br> -->
            
            <label for="file">Image file</label>
            <input type="file" id="file" name="file" accept="image/*" required>
        
            <button type="submit" class="button">Create</button>
        </form>
</div>
