<link rel="stylesheet" href="stylesheets/card.css">
<link rel="stylesheet" href="stylesheets/validations.css">
<div id="card">
    <h2>Edit Profile</h2>
    <form method="post" enctype="multipart/form-data" action="<?= $this->baseUrl() ?>/edit_profile">

        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <p class="validation">
           <?php echo $this -> usernamevalidationError ; ?>
        </p>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" placeholder="New Password" required>
         <p class="validation">
           <?php echo $this -> passwordvalidationError ; 
?>

        <input type="file" class="urlAvatar" name="urlAvatar" id="urAvatar" accept="image/png, image/jpeg">
        <button type="submit" class="button" editProfileAction>Save Changes</button>

    </form>



</div>