<link rel="stylesheet" href="stylesheets/card.css">
<link rel="stylesheet" href="stylesheets/validations.css">
<div id="card">
    <h2>Edit Profile</h2>
    <form method="post" enctype="multipart/form-data" action="<?= $this->baseUrl() ?>/edit_profile">

        <label for="username">Username:</label>
        <input type="text" id="username" name="username" placeholder="New Username">
        <p class="validation">
           <?php echo $this -> usernamevalidationError ; ?>
        </p>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" placeholder="New Password">
         <p class="validation">
           <?php echo $this -> passwordvalidationError ;?>
        </p>
<div class="avatar-upload">
    <input 
        type="file" 
        name="urlAvatar" 
        id="urlAvatar" 
        accept="image/png, image/jpeg"
    >
    <label for="urlAvatar" class="avatar-button">
        <i class="fa-solid fa-user"></i>
        Choose Avatar
    </label>
</div>  
<button type="submit" class="button" editProfileAction>Save Changes</button>
    </form>

</div>