<style>
    <?php include 'stylesheets/listFilms.css'; ?>
</style>

<div class="options-btn">
    <button onclick="location.href='/addFilm'"> ➕ Añadir Pelicula</button>
    <button onclick="location.href='/updateFilm'">✏️ Modificar Pelicula</button>
    <button onclick="location.href='/deleteFilm'">❌ Eliminar Pelicula</button>
</div>

<div class="list-films-container">

<?php foreach ($this->moviesData as $movie): ?>

    <div class="movie-card">
        <img src="<?= $movie["imagePath"] ?>" alt="<?= $movie["name"] ?>">
        <h3><?= $movie["name"] ?></h3>
        <p><?= $movie["description"] ?></p>
        <p class="category"><?= $movie["categoryName"] ?></p>
    </div>

<?php endforeach; ?>

</div>
