<?php $moviesData = Movie::getAllMovies(); ?>

<style>
    <?php include 'stylesheets/listFilms.css'; ?>
</style>

<div class="options-btn">
    <button onclick="location.href='/addFilm'"> ➕ Añadir Pelicula</button>
    <button onclick="location.href='/updateFilm'">✏️ Modificar Pelicula</button>
    <button onclick="location.href='/deleteFilm'">❌ Eliminar Pelicula</button>
</div>

<div class="list-films-container">

<?php foreach ($this -> moviesData as $movie): ?>

    <?php
        if (!empty($movie["urlImage"])) {
            $imagePath = $movie["urlImage"];
        } else {
            $imagePath = strtolower(str_replace(" ", "", $movie["name"])) . ".jpg";
        }

        $isBuyed = in_array($movie["id"], $this -> filmsBuyedByUser);
    ?>

    <div class="movie-card">
        <img src="<?= $imagePath ?>" alt="<?= $movie["name"] ?>">
        <h3><?= $movie["name"] ?></h3>
        <p><?= $movie["description"] ?></p>

        <?php if (!$isBuyed): ?>
            <form action="<?= $this->baseUrl() ?>/buyFilm" method="POST">
                <input type="hidden" name="filmId" value="<?= $movie['id'] ?>">
                <button type="submit">Buy Film</button>
            </form>        
        <?php else: ?>
            <button disabled>✔ Comprada</button>
        <?php endif; ?>

    </div>

<?php endforeach; ?>


</div>
