<style>
    <?php include 'stylesheets/home.css';
     ?>
</style>
<div class="container">
    <div class="logo-animation">
        <div class="play-icon"></div>
    </div>

    <h1>Welcome to MovieList</h1>
    <p>Lorem ipsum</p>

    <div class="movie-grid">
    <div class="movie-card">
        <img src="images/filmCovers/avatar.jpg" alt="Película 1">
    </div>
    <div class="movie-card">
        <img src="images/filmCovers/tenet.jpg" alt="Película 2">
    </div>
    <div class="movie-card">
        <img src="images/filmCovers/jjk.jpg" alt="Película 3">
    </div>
    <div class="movie-card">
        <img src="images/filmCovers/oppenheimer.jpg" alt="Película 4">
    </div>
</div>
</div>
