
<style>
    <?php include 'stylesheets/style.css'; ?>
</style>

<div class="submenu">
    <a href="<?= $this->baseUrl() ?>/createCategories">Create category</a>
    <a href="<?= $this->baseUrl() ?>/deleteCategories">Delete category</a>
</div>

<div class="container">
    <h2>Update category</h2>
    <form method="post" action="<?= $this->baseUrl() ?>/updateCategories" enctype="multipart/form-data">
        <label for="name">Name</label>
        <select name="id">
            <?php foreach ($this -> data["category"] as $cat): ?> 
                <option  value="<?= $cat['id'] ?>"><?= $cat['name'] ?></option>
            <?php endforeach; ?>
        </select>
        
        <label for="description">Description</label>
        <input type="text" id="description" name="description" required>
        
        <label for="file">Image file</label>
        <input type="file" id="file" name="file" accept="image/*">
        <input type="hidden" name="urlCategoryImg" value="<?= $this->category['urlCategoryImg'] ?? '' ?>">

        <button type="submit" class="button">Update</button>
    </form>
</div>    
