<style>
	<?php include 'stylesheets/layout.css';?>
</style>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<header>
	<nav>
		<ul>
			<li><a href="<?= $this->baseUrl() ?>/home">Home</a></li>
			<li><a href="<?= $this->baseUrl() ?>/register">Register</a></li>
			<li><a href="<?= $this->baseUrl() ?>/login">Login</a></li>
			<li><a href="<?= $this->baseUrl() ?>/listFilms">List Films</a></li>
			<li><a href="<?= $this->baseUrl() ?>/logout">Logout</a></li>
		</ul>
</header>
<body>
	<?php echo $this->content(); ?>
</body>
<footer>
	<p>&copy; 2025 Developers Sprint 3</p>
</footer>
</html>